POST http://localhost:3003/api/blogs  HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNhbWlsbGVsZW5vcm1hbmRAZmFrZS5jb20iLCJpZCI6IjY0ZDM3MTc5YmMxMGQ4YzRjOWU0ZjY4NyIsImlhdCI6MTY5MTU4NDM4MX0.7eZRJ5UFwyzLosy1o8svhQeICtfmJKnqxSDgg37pyfs

{
  "title": "Hello World Blog created with Bearer token",
  "author": "John Doe",
  "url": "https://helloworld.com",
  "likes": 2,
  "userId": "64d35c6498ec5c50460daa65"
}
